from app import app, db
from models import *

def insertToAllTables():
    try:
        with app.app_context():
            Tags.query.delete()
            Tags_details.query.delete()
            Skills.query.delete()
            Skills_details.query.delete()
            Activity.query.delete()
            Communication.query.delete()
            Activity_details.query.delete()
            Communication_details.query.delete()
            Lead.query.delete()
            Lead_details.query.delete()
            User.query.delete()
            User_details.query.delete()

            db.session.commit()
            
            user_details_1 = User_details(url_image='https://images.immediate.co.uk/production/volatile/sites/10/2018/02/4f492b22-2d29-4360-80a6-79879487c7b7-e07922e.jpg?quality=90&fit=700,466', firstname='John', lastname='Doe', email='2@email.com', job_title='Manager', phone='1234567890', addres='123 Main St',     password='12345678')
            user_details_2 = User_details(url_image='https://images.immediate.co.uk/production/volatile/sites/10/2018/02/4f492b22-2d29-4360-80a6-79879487c7b7-e07922e.jpg?quality=90&fit=700,466', firstname='Ja', lastname='Smith', email='1@email.com', job_title='Developer', phone='0987654321', addres='456 Second St', password='87654321')
            user_details_3 = User_details(url_image='https://images.immediate.co.uk/production/volatile/sites/10/2018/02/4f492b22-2d29-4360-80a6-79879487c7b7-e07922e.jpg?quality=90&fit=700,466', firstname='Hik', lastname='Blob', email='3@email.com', job_title='Boss', phone='0967954321', addres='789 Third St',       password='13579246')
            
            db.session.add(user_details_1)
            db.session.add(user_details_2)
            db.session.add(user_details_3)
            db.session.commit()

            user_1 = User(user_basic_details=user_details_1.id)
            user_2 = User(user_basic_details=user_details_2.id)
            user_3 = User(user_basic_details=user_details_3.id)

            db.session.add(user_1)
            db.session.add(user_2)
            db.session.add(user_3)
            db.session.commit()
            
            lead_details_1 = Lead_details(url_image='https://images.immediate.co.uk/production/volatile/sites/10/2018/02/4f492b22-2d29-4360-80a6-79879487c7b7-e07922e.jpg?quality=90&fit=700,466', firstname='Alice', lastname='Johnson', ORGANIZATION='Company A', email='alice@company.com', phone_number='1234567890', addres='789 Third St')
            lead_details_2 = Lead_details(url_image='https://images.immediate.co.uk/production/volatile/sites/10/2018/02/4f492b22-2d29-4360-80a6-79879487c7b7-e07922e.jpg?quality=90&fit=700,466', firstname='Bob',   lastname='Smith',   ORGANIZATION='Company B', email='bob@company.com',   phone_number='0987654321', addres='123 Fourth St')
            lead_details_3 = Lead_details(url_image='https://images.immediate.co.uk/production/volatile/sites/10/2018/02/4f492b22-2d29-4360-80a6-79879487c7b7-e07922e.jpg?quality=90&fit=700,466', firstname='Black',   lastname='George',   ORGANIZATION='Company C', email='blacker@company.com',   phone_number='455645674321', addres='564 Fifth St')

            db.session.add(lead_details_1)
            db.session.add(lead_details_2)
            db.session.add(lead_details_3)
            db.session.commit()
            
            lead_1 = Lead(firstname='Alice', lead_details=lead_details_1.id)
            lead_2 = Lead(firstname='Bob',   lead_details=lead_details_2.id)
            lead_3 = Lead(firstname='Black',   lead_details=lead_details_3.id)

            db.session.add(lead_1)
            db.session.add(lead_2)
            db.session.add(lead_3)
            
            db.session.commit()
            
            activity_details_1 = Activity_details(title='Meeting',  activity_type='Call', user=user_1.id)
            activity_details_2 = Activity_details(title='Sleeping', activity_type='Rest', user=user_1.id)
            activity_details_3 = Activity_details(title='Eating', activity_type='Meal', user=user_1.id)
            activity_details_4 = Activity_details(title='Sitting', activity_type='Rest', user=user_2.id)
            activity_details_5 = Activity_details(title='Writing', activity_type='Working', user=user_2.id)
            activity_details_6 = Activity_details(title='reading', activity_type='Working', user=user_2.id)
            activity_details_7 = Activity_details(title='Cheecking', activity_type='Working', user=user_3.id)
            activity_details_8 = Activity_details(title='Speaking', activity_type='Working', user=user_3.id)
            activity_details_9 = Activity_details(title='Resting', activity_type='Rest', user=user_3.id)

            db.session.add(activity_details_1)
            db.session.add(activity_details_2)
            db.session.add(activity_details_3)
            db.session.add(activity_details_4)
            db.session.add(activity_details_5)
            db.session.add(activity_details_6)
            db.session.add(activity_details_7)
            db.session.add(activity_details_8)
            db.session.add(activity_details_9)
            db.session.commit()
            
            activity_1 = Activity(lead=lead_details_1.id, activity_details=activity_details_1.id)
            activity_2 = Activity(lead=lead_details_1.id, activity_details=activity_details_8.id)
            activity_3 = Activity(lead=lead_details_1.id, activity_details=activity_details_6.id)
        
            activity_4 = Activity(lead=lead_details_2.id, activity_details=activity_details_2.id)
            activity_5 = Activity(lead=lead_details_2.id, activity_details=activity_details_3.id)
            activity_6 = Activity(lead=lead_details_2.id, activity_details=activity_details_4.id)
            
            activity_7 = Activity(lead=lead_details_3.id, activity_details=activity_details_5.id)
            activity_8 = Activity(lead=lead_details_3.id, activity_details=activity_details_9.id)
            activity_9 = Activity(lead=lead_details_3.id, activity_details=activity_details_7.id)

            db.session.add(activity_1)
            db.session.add(activity_2)
            db.session.add(activity_3)
            db.session.add(activity_4)
            db.session.add(activity_5)
            db.session.add(activity_6)
            db.session.add(activity_7)
            db.session.add(activity_8)
            db.session.add(activity_9)
            db.session.commit()
            
            communication_details = Communication_details(subject='Follow up', text='Following up', user=user_1.id)
            communication_details_1 = Communication_details(subject='Active', text='Active', user=user_1.id)
            communication_details_2 = Communication_details(subject='Online', text='Online', user=user_1.id)
            
            communication_details_3 = Communication_details(subject='Offline', text='Offline', user=user_2.id)
            communication_details_4 = Communication_details(subject='Unactive', text='Unactive', user=user_2.id)
            communication_details_5 = Communication_details(subject='Unfollow', text='Unfollow', user=user_2.id)

            communication_details_6 = Communication_details(subject='Offline', text='Offline', user=user_3.id)
            communication_details_7 = Communication_details(subject='Unactive', text='Unactive', user=user_3.id)
            communication_details_8 = Communication_details(subject='Follow up', text='Following up', user=user_3.id)
            
            db.session.add(communication_details)
            db.session.add(communication_details_1)
            db.session.add(communication_details_2)
            db.session.add(communication_details_3)
            db.session.add(communication_details_4)
            db.session.add(communication_details_5)
            db.session.add(communication_details_6)
            db.session.add(communication_details_7)
            db.session.add(communication_details_8)
            db.session.commit()
            
            communication_1 = Communication(lead=lead_1.id, communication_details=communication_details.id)
            communication_2 = Communication(lead=lead_1.id, communication_details=communication_details_1.id)
            communication_3 = Communication(lead=lead_1.id, communication_details=communication_details_2.id)
            
            communication_4 = Communication(lead=lead_2.id, communication_details=communication_details_3.id)
            communication_5 = Communication(lead=lead_2.id, communication_details=communication_details_4.id)
            communication_6 = Communication(lead=lead_2.id, communication_details=communication_details_5.id)
            
            communication_7 = Communication(lead=lead_3.id, communication_details=communication_details_6.id)
            communication_8 = Communication(lead=lead_3.id, communication_details=communication_details_7.id)
            communication_9 = Communication(lead=lead_3.id, communication_details=communication_details_8.id)

            db.session.add(communication_1)
            db.session.add(communication_2)
            db.session.add(communication_3)
            db.session.add(communication_4)
            db.session.add(communication_5)
            db.session.add(communication_6)
            db.session.add(communication_7)
            db.session.add(communication_8)
            db.session.add(communication_9)
            db.session.commit()
            
            skills_details_3 = Skills_details(title='Flask')
            skills_details_4 = Skills_details(title='HTML')
            skills_details_5 = Skills_details(title='Figma')
            
            skills_details = Skills_details(title='Python')
            skills_details1 = Skills_details(title='Javascript')
            skills_details2 = Skills_details(title='CSS')
            
            skills_details_6 = Skills_details(title='C#')
            skills_details_7 = Skills_details(title='C++')
            skills_details_8 = Skills_details(title='Django')

            db.session.add(skills_details)
            db.session.add(skills_details1)
            db.session.add(skills_details2)
            db.session.add(skills_details_3)
            db.session.add(skills_details_4)
            db.session.add(skills_details_5)
            db.session.add(skills_details_6)
            db.session.add(skills_details_7)
            db.session.add(skills_details_8)
            db.session.commit()
            
            skills_1 = Skills(lead=lead_1.id, skills_details=skills_details.id)
            skills_2 = Skills(lead=lead_1.id, skills_details=skills_details1.id)
            skills_3 = Skills(lead=lead_1.id, skills_details=skills_details2.id)
            
            skills_4 = Skills(lead=lead_2.id, skills_details=skills_details_3.id)
            skills_5 = Skills(lead=lead_2.id, skills_details=skills_details_4.id)
            skills_6 = Skills(lead=lead_2.id, skills_details=skills_details_5.id)
            
            skills_7 = Skills(lead=lead_3.id, skills_details=skills_details_6.id)
            skills_8 = Skills(lead=lead_3.id, skills_details=skills_details_7.id)
            skills_9 = Skills(lead=lead_3.id, skills_details=skills_details_8.id)

            db.session.add(skills_1)
            db.session.add(skills_2)
            db.session.add(skills_3)
            db.session.add(skills_4)
            db.session.add(skills_5)
            db.session.add(skills_6)
            db.session.add(skills_7)
            db.session.add(skills_8)
            db.session.add(skills_9)
            db.session.commit()
            
            tags_details = Tags_details(title='EXPERT')
            tags_details_1 = Tags_details(title='BEGGINER')
            tags_details_2 = Tags_details(title='INTERMEDIATE')
            tags_details_3 = Tags_details(title='ADMIN')
            tags_details_4 = Tags_details(title='SUPERADMIN')
            tags_details_5 = Tags_details(title='HELPER')
            tags_details_6 = Tags_details(title='BLOCKED')
            tags_details_7 = Tags_details(title='CONTACT')
            tags_details_8 = Tags_details(title='EXPERT')

            db.session.add(tags_details)
            db.session.add(tags_details_1)
            db.session.add(tags_details_2)
            db.session.add(tags_details_3)
            db.session.add(tags_details_4)
            db.session.add(tags_details_5)
            db.session.add(tags_details_6)
            db.session.add(tags_details_7)
            db.session.add(tags_details_8)
            db.session.commit()

            tags_1 = Tags(lead=lead_1.id, tags_details=tags_details.id)
            tags_2 = Tags(lead=lead_1.id, tags_details=tags_details_1.id)
            tags_3 = Tags(lead=lead_1.id, tags_details=tags_details_2.id)
            
            tags_4 = Tags(lead=lead_2.id, tags_details=tags_details_3.id)
            tags_5 = Tags(lead=lead_2.id, tags_details=tags_details_4.id)
            tags_6 = Tags(lead=lead_2.id, tags_details=tags_details_5.id)
            
            tags_7 = Tags(lead=lead_3.id, tags_details=tags_details_6.id)
            tags_8 = Tags(lead=lead_3.id, tags_details=tags_details_7.id)
            tags_9 = Tags(lead=lead_3.id, tags_details=tags_details_8.id)

            db.session.add(tags_1)
            db.session.add(tags_2)
            db.session.add(tags_3)
            db.session.add(tags_4)
            db.session.add(tags_5)
            db.session.add(tags_6)
            db.session.add(tags_7)
            db.session.add(tags_8)
            db.session.add(tags_9)
            db.session.commit()
            
    except Exception as e:
        print(f'Inserting data error.\nError: {e}')